spring.application.name=fichestu
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/fichestu_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=${HIBERNATE_SHOW_SQL:false}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.connect-retries=30
