CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    profile_pic_url TEXT,
    fiat_balance NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS badges (
    badge_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    icon_url TEXT,
    description TEXT
);

CREATE TABLE IF NOT EXISTS user_badges (
    user_id INTEGER NOT NULL,
    badge_id INTEGER NOT NULL,
    awarded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, badge_id),
    CONSTRAINT fk_user_badges_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_badges_badge FOREIGN KEY (badge_id) REFERENCES badges(badge_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tokens (
    token_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    color_code VARCHAR(7),
    current_price NUMERIC(15, 2) NOT NULL DEFAULT 10.00,
    last_update TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_wallets (
    user_id INTEGER NOT NULL,
    token_id INTEGER NOT NULL,
    quantity NUMERIC(15, 4) NOT NULL DEFAULT 0.0000,
    PRIMARY KEY (user_id, token_id),
    CONSTRAINT fk_user_wallets_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_wallets_token FOREIGN KEY (token_id) REFERENCES tokens(token_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS token_price_history (
    history_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_id INTEGER NOT NULL,
    price NUMERIC(15, 2) NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_token_price_history_token FOREIGN KEY (token_id) REFERENCES tokens(token_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS game_sessions (
    match_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(20) NOT NULL DEFAULT 'WAITING',
    start_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP WITH TIME ZONE NULL,
    winner_id INTEGER NULL,
    CONSTRAINT fk_game_sessions_winner FOREIGN KEY (winner_id) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS match_participants (
    match_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    selected_ball_number INTEGER DEFAULT NULL,
    multiplier_won NUMERIC(10, 2) NOT NULL DEFAULT 1.00,
    current_hp INTEGER NOT NULL DEFAULT 50,
    is_alive BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (match_id, user_id),
    CONSTRAINT fk_match_participants_match FOREIGN KEY (match_id) REFERENCES game_sessions(match_id) ON DELETE CASCADE,
    CONSTRAINT fk_match_participants_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS match_cards (
    card_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INTEGER,
    owner_id INTEGER,
    card_type VARCHAR(20),
    card_value INTEGER,
    is_used BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_match_cards_match FOREIGN KEY (match_id) REFERENCES game_sessions(match_id) ON DELETE CASCADE,
    CONSTRAINT fk_match_cards_owner FOREIGN KEY (owner_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS transactions_log (
    transaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    type VARCHAR(50),
    amount_fiat NUMERIC(15, 2),
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transactions_log_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

INSERT INTO tokens (name, color_code, current_price) VALUES
('Ficha Roja', '#FF0000', 50.00),
('Ficha Azul', '#0000FF', 25.00),
('Ficha Verde', '#00FF00', 10.00),
('Ficha Dorada', '#FFD700', 100.00)
ON CONFLICT DO NOTHING;

INSERT INTO users (username, email, password_hash, role, fiat_balance)
VALUES ('SuperAdmin', 'admin@fichestu.local', 'admin123', 'ADMIN', 999999.99)
ON CONFLICT (email) DO NOTHING;

INSERT INTO users (username, email, password_hash, role, fiat_balance)
VALUES ('Jugador1', 'player@test.com', 'pass123', 'USER', 100.00)
ON CONFLICT (email) DO NOTHING;
