CREATE TABLE IF NOT EXISTS minigame_attempts (
    attempt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    game_type VARCHAR(40) NOT NULL,
    payment_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'STARTED',
    entry_cost NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    reward_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    score INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_minigame_attempts_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_minigame_attempts_user_game_started
    ON minigame_attempts (user_id, game_type, payment_type, started_at DESC);
