CREATE TABLE IF NOT EXISTS revoked_jwt_tokens (
    revoked_token_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    user_id INTEGER NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason VARCHAR(50),
    CONSTRAINT fk_revoked_jwt_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_revoked_jwt_tokens_hash_expires
    ON revoked_jwt_tokens (token_hash, expires_at);

CREATE INDEX IF NOT EXISTS idx_revoked_jwt_tokens_expires_at
    ON revoked_jwt_tokens (expires_at);
