/*
Fichestu cloud DB stress test and synthetic data load.

Target: PostgreSQL/Supabase.
Safety: this script uses only schema "fichestu_stress". It does not write to
public app tables. Re-run safe: it drops/recreates only fichestu_stress.

How to run with psql:
  psql "$DATABASE_URL" -f docs/stress-test-cloud-db.sql

Where results are stored:
  SELECT * FROM fichestu_stress.stress_results ORDER BY step_order;
  SELECT * FROM fichestu_stress.stress_explain_lines ORDER BY plan_name, line_no;
  SELECT * FROM fichestu_stress.stress_capacity_report ORDER BY total_bytes DESC;

Cleanup when finished:
  DROP SCHEMA IF EXISTS fichestu_stress CASCADE;
*/

DROP SCHEMA IF EXISTS fichestu_stress CASCADE;
CREATE SCHEMA fichestu_stress;

SET search_path TO fichestu_stress, public;
SET client_min_messages TO WARNING;

CREATE TABLE stress_config (
    config_key TEXT PRIMARY KEY,
    config_value INTEGER NOT NULL
);

INSERT INTO stress_config (config_key, config_value) VALUES
    ('user_count', 10000),
    ('token_count', 5),
    ('price_points_per_token', 10000),
    ('session_count', 4000),
    ('participants_per_session', 8),
    ('cards_per_session', 6),
    ('transactions_per_user', 3),
    ('notifications_per_user', 5),
    ('minigame_attempts_per_user', 2),
    ('workload_iterations', 10);

CREATE TABLE stress_runs (
    run_id TEXT PRIMARY KEY,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT clock_timestamp(),
    finished_at TIMESTAMP WITH TIME ZONE NULL,
    db_name TEXT NOT NULL DEFAULT current_database(),
    db_user TEXT NOT NULL DEFAULT current_user,
    server_version TEXT NOT NULL DEFAULT current_setting('server_version'),
    config JSONB NOT NULL
);

CREATE TABLE stress_results (
    step_order INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL,
    step_name TEXT NOT NULL,
    rows_affected BIGINT NOT NULL DEFAULT 0,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_ms NUMERIC(14, 3) NOT NULL,
    notes TEXT NULL
);

CREATE TABLE stress_explain_lines (
    run_id TEXT NOT NULL,
    plan_name TEXT NOT NULL,
    line_no INTEGER NOT NULL,
    plan_line TEXT NOT NULL,
    PRIMARY KEY (run_id, plan_name, line_no)
);

CREATE TABLE stress_capacity_report (
    run_id TEXT NOT NULL,
    relation_name TEXT NOT NULL,
    estimated_rows BIGINT NOT NULL,
    table_bytes BIGINT NOT NULL,
    index_bytes BIGINT NOT NULL,
    total_bytes BIGINT NOT NULL,
    captured_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (run_id, relation_name)
);

CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255),
    profile_pic_url TEXT,
    fiat_balance NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    preferred_language VARCHAR(10) NOT NULL DEFAULT 'es',
    profile_title VARCHAR(80),
    profile_bio TEXT,
    profile_page_background TEXT
);

CREATE TABLE badges (
    badge_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    icon_url TEXT,
    description TEXT
);

CREATE TABLE user_badges (
    user_id INTEGER NOT NULL,
    badge_id INTEGER NOT NULL,
    awarded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, badge_id),
    CONSTRAINT fk_stress_user_badges_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_stress_user_badges_badge FOREIGN KEY (badge_id) REFERENCES badges(badge_id) ON DELETE CASCADE
);

CREATE TABLE tokens (
    token_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    color_code VARCHAR(7),
    current_price NUMERIC(15, 2) NOT NULL DEFAULT 10.00,
    last_update TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_wallets (
    user_id INTEGER NOT NULL,
    token_id INTEGER NOT NULL,
    quantity NUMERIC(15, 4) NOT NULL DEFAULT 0.0000,
    PRIMARY KEY (user_id, token_id),
    CONSTRAINT fk_stress_user_wallets_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_stress_user_wallets_token FOREIGN KEY (token_id) REFERENCES tokens(token_id) ON DELETE CASCADE
);

CREATE TABLE token_price_history (
    history_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_id INTEGER NOT NULL,
    price NUMERIC(15, 2) NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stress_token_price_history_token FOREIGN KEY (token_id) REFERENCES tokens(token_id) ON DELETE CASCADE
);

CREATE TABLE game_sessions (
    match_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(20) NOT NULL DEFAULT 'WAITING',
    start_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP WITH TIME ZONE NULL,
    winner_id INTEGER NULL,
    matchmaking_deadline TIMESTAMP WITH TIME ZONE NULL,
    ball_pick_deadline TIMESTAMP WITH TIME ZONE NULL,
    battle_round_deadline TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_stress_game_sessions_winner FOREIGN KEY (winner_id) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE TABLE match_participants (
    match_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    selected_ball_number INTEGER DEFAULT NULL,
    multiplier_won NUMERIC(10, 2) NOT NULL DEFAULT 1.00,
    current_hp INTEGER NOT NULL DEFAULT 50,
    is_alive BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (match_id, user_id),
    CONSTRAINT fk_stress_match_participants_match FOREIGN KEY (match_id) REFERENCES game_sessions(match_id) ON DELETE CASCADE,
    CONSTRAINT fk_stress_match_participants_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE match_cards (
    card_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INTEGER,
    owner_id INTEGER,
    card_type VARCHAR(20),
    card_value INTEGER,
    is_used BOOLEAN NOT NULL DEFAULT FALSE,
    round_number INTEGER NULL,
    target_user_id INTEGER NULL,
    CONSTRAINT fk_stress_match_cards_match FOREIGN KEY (match_id) REFERENCES game_sessions(match_id) ON DELETE CASCADE,
    CONSTRAINT fk_stress_match_cards_owner FOREIGN KEY (owner_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE transactions_log (
    transaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    type VARCHAR(50),
    amount_fiat NUMERIC(15, 2),
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stress_transactions_log_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE market_reset_audit (
    reset_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_date DATE NOT NULL UNIQUE,
    zone_id VARCHAR(64) NOT NULL,
    summary TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game_session_events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INTEGER NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    payload TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stress_game_session_events_match FOREIGN KEY (match_id) REFERENCES game_sessions(match_id) ON DELETE CASCADE
);

CREATE TABLE password_reset_tokens (
    reset_token_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stress_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE notifications (
    notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    title VARCHAR(120) NOT NULL,
    body TEXT NOT NULL,
    type VARCHAR(40) NOT NULL DEFAULT 'INFO',
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stress_notifications_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE revoked_jwt_tokens (
    revoked_token_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    user_id INTEGER NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stress_revoked_jwt_tokens_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE TABLE minigame_attempts (
    attempt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    game_type VARCHAR(40) NOT NULL,
    payment_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'STARTED',
    entry_cost NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    reward_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    score INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_stress_minigame_attempts_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX idx_token_price_history_token_recorded ON token_price_history (token_id, recorded_at DESC);
CREATE INDEX idx_game_sessions_status_start ON game_sessions (status, start_time DESC);
CREATE INDEX idx_match_cards_match_round ON match_cards (match_id, round_number);
CREATE INDEX idx_match_cards_owner_used ON match_cards (owner_id, is_used);
CREATE INDEX idx_transactions_user_created ON transactions_log (user_id, created_at DESC);
CREATE INDEX idx_game_session_events_match_created ON game_session_events (match_id, created_at DESC);
CREATE INDEX idx_password_reset_tokens_user_created ON password_reset_tokens (user_id, created_at DESC);
CREATE INDEX idx_password_reset_tokens_expires ON password_reset_tokens (expires_at);
CREATE INDEX idx_notifications_user_created ON notifications (user_id, created_at DESC);
CREATE INDEX idx_notifications_user_read ON notifications (user_id, is_read);
CREATE INDEX idx_revoked_jwt_tokens_hash_expires ON revoked_jwt_tokens (token_hash, expires_at);
CREATE INDEX idx_revoked_jwt_tokens_expires_at ON revoked_jwt_tokens (expires_at);
CREATE INDEX idx_minigame_attempts_user_game_started ON minigame_attempts (user_id, game_type, payment_type, started_at DESC);

DO $$
DECLARE
    v_run_id TEXT := to_char(clock_timestamp(), 'YYYYMMDDHH24MISSMS') || '-' || txid_current();
    v_start TIMESTAMP WITH TIME ZONE;
    v_rows BIGINT;
    v_user_count INTEGER;
    v_token_count INTEGER;
    v_price_points_per_token INTEGER;
    v_session_count INTEGER;
    v_participants_per_session INTEGER;
    v_cards_per_session INTEGER;
    v_transactions_per_user INTEGER;
    v_notifications_per_user INTEGER;
    v_minigame_attempts_per_user INTEGER;
    v_workload_iterations INTEGER;
    v_i INTEGER;
    v_plan_line TEXT;
    v_line_no INTEGER;
BEGIN
    SELECT config_value INTO v_user_count FROM stress_config WHERE config_key = 'user_count';
    SELECT config_value INTO v_token_count FROM stress_config WHERE config_key = 'token_count';
    SELECT config_value INTO v_price_points_per_token FROM stress_config WHERE config_key = 'price_points_per_token';
    SELECT config_value INTO v_session_count FROM stress_config WHERE config_key = 'session_count';
    SELECT config_value INTO v_participants_per_session FROM stress_config WHERE config_key = 'participants_per_session';
    SELECT config_value INTO v_cards_per_session FROM stress_config WHERE config_key = 'cards_per_session';
    SELECT config_value INTO v_transactions_per_user FROM stress_config WHERE config_key = 'transactions_per_user';
    SELECT config_value INTO v_notifications_per_user FROM stress_config WHERE config_key = 'notifications_per_user';
    SELECT config_value INTO v_minigame_attempts_per_user FROM stress_config WHERE config_key = 'minigame_attempts_per_user';
    SELECT config_value INTO v_workload_iterations FROM stress_config WHERE config_key = 'workload_iterations';

    INSERT INTO stress_runs (run_id, config)
    SELECT v_run_id, jsonb_object_agg(config_key, config_value)
    FROM stress_config;

    v_start := clock_timestamp();
    INSERT INTO badges (name, icon_url, description)
    SELECT 'Stress Badge ' || gs, '/badges/stress-' || gs || '.png', 'Synthetic stress-test badge ' || gs
    FROM generate_series(1, 20) AS gs;
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'load badges', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

    v_start := clock_timestamp();
    INSERT INTO tokens (name, color_code, current_price, last_update)
    SELECT
        'Stress Token ' || gs,
        '#' || lpad(to_hex((gs * 654321) % 16777215), 6, '0'),
        ROUND((1 + random() * 499)::numeric, 2),
        clock_timestamp()
    FROM generate_series(1, v_token_count) AS gs;
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'load tokens', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

    v_start := clock_timestamp();
    INSERT INTO users (username, email, password_hash, fiat_balance, role, created_at, preferred_language, profile_title, profile_bio, profile_page_background)
    SELECT
        'stress_user_' || gs,
        'stress_user_' || gs || '@loadtest.fichestu.local',
        'stress_hash_' || gs,
        ROUND((random() * 10000)::numeric, 2),
        CASE WHEN gs % 1000 = 0 THEN 'ADMIN' ELSE 'USER' END,
        clock_timestamp() - ((gs % 365) || ' days')::interval,
        CASE WHEN gs % 3 = 0 THEN 'en' ELSE 'es' END,
        'Stress profile ' || gs,
        'Synthetic profile generated for cloud database stress testing.',
        CASE WHEN gs % 4 = 0 THEN 'preset:aurora' ELSE 'preset:casino' END
    FROM generate_series(1, v_user_count) AS gs;
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'load users', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

    v_start := clock_timestamp();
    INSERT INTO user_wallets (user_id, token_id, quantity)
    SELECT u.user_id, t.token_id, ROUND((random() * 250)::numeric, 4)
    FROM users u
    CROSS JOIN tokens t;
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'load wallets', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

    v_start := clock_timestamp();
    INSERT INTO user_badges (user_id, badge_id, awarded_at)
    SELECT u.user_id, ((u.user_id % 20) + 1), clock_timestamp() - ((u.user_id % 90) || ' days')::interval
    FROM users u
    WHERE u.user_id % 3 = 0;
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'load user badges', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

    v_start := clock_timestamp();
    INSERT INTO token_price_history (token_id, price, recorded_at)
    SELECT
        t.token_id,
        ROUND((t.current_price * (0.5 + random()))::numeric, 2),
        clock_timestamp() - ((gs % 1440) || ' minutes')::interval
    FROM tokens t
    CROSS JOIN generate_series(1, v_price_points_per_token) AS gs;
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'load token price history', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

    v_start := clock_timestamp();
    INSERT INTO game_sessions (status, start_time, end_time, winner_id, matchmaking_deadline, ball_pick_deadline, battle_round_deadline)
    SELECT
        CASE WHEN gs % 5 = 0 THEN 'FINISHED' WHEN gs % 5 = 1 THEN 'WAITING' ELSE 'BATTLE' END,
        clock_timestamp() - ((gs % 10080) || ' minutes')::interval,
        CASE WHEN gs % 5 = 0 THEN clock_timestamp() - ((gs % 1000) || ' minutes')::interval ELSE NULL END,
        CASE WHEN gs % 5 = 0 THEN ((gs % v_user_count) + 1) ELSE NULL END,
        clock_timestamp() + '2 minutes'::interval,
        clock_timestamp() + '5 minutes'::interval,
        clock_timestamp() + '8 minutes'::interval
    FROM generate_series(1, v_session_count) AS gs;
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'load game sessions', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

    v_start := clock_timestamp();
    INSERT INTO match_participants (match_id, user_id, selected_ball_number, multiplier_won, current_hp, is_alive)
    SELECT
        s.match_id,
        (((s.match_id - 1) * v_participants_per_session + p.participant_no - 1) % v_user_count) + 1,
        p.participant_no,
        ROUND((0.5 + random() * 5)::numeric, 2),
        10 + ((s.match_id + p.participant_no) % 90),
        ((s.match_id + p.participant_no) % 7) <> 0
    FROM game_sessions s
    CROSS JOIN generate_series(1, v_participants_per_session) AS p(participant_no);
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'load match participants', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

    v_start := clock_timestamp();
    INSERT INTO match_cards (match_id, owner_id, card_type, card_value, is_used, round_number, target_user_id)
    SELECT
        s.match_id,
        (((s.match_id - 1) * v_cards_per_session + c.card_no - 1) % v_user_count) + 1,
        CASE c.card_no % 3 WHEN 0 THEN 'ATTACK' WHEN 1 THEN 'DEFENSE' ELSE 'HEAL' END,
        5 + ((s.match_id + c.card_no) % 25),
        c.card_no % 4 = 0,
        ((c.card_no - 1) / 2) + 1,
        (((s.match_id - 1) * v_cards_per_session + c.card_no + 11) % v_user_count) + 1
    FROM game_sessions s
    CROSS JOIN generate_series(1, v_cards_per_session) AS c(card_no);
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'load match cards', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

    v_start := clock_timestamp();
    INSERT INTO game_session_events (match_id, event_type, payload, created_at)
    SELECT s.match_id, 'STRESS_EVENT', '{"source":"stress-test"}', s.start_time + ((e.event_no * 10) || ' seconds')::interval
    FROM game_sessions s
    CROSS JOIN generate_series(1, 3) AS e(event_no);
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'load game events', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

    v_start := clock_timestamp();
    INSERT INTO transactions_log (user_id, type, amount_fiat, description, created_at)
    SELECT
        u.user_id,
        CASE gs % 3 WHEN 0 THEN 'BUY' WHEN 1 THEN 'SELL' ELSE 'REWARD' END,
        ROUND((random() * 500)::numeric, 2),
        'Synthetic stress transaction',
        clock_timestamp() - ((u.user_id + gs) % 10000 || ' minutes')::interval
    FROM users u
    CROSS JOIN generate_series(1, v_transactions_per_user) AS gs;
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'load transactions', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

    v_start := clock_timestamp();
    INSERT INTO notifications (user_id, title, body, type, is_read, created_at)
    SELECT
        u.user_id,
        'Stress notification ' || gs,
        'Synthetic notification body for stress testing.',
        CASE gs % 3 WHEN 0 THEN 'GAME' WHEN 1 THEN 'MARKET' ELSE 'PROFILE' END,
        gs % 2 = 0,
        clock_timestamp() - ((u.user_id + gs) % 5000 || ' minutes')::interval
    FROM users u
    CROSS JOIN generate_series(1, v_notifications_per_user) AS gs;
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'load notifications', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

    v_start := clock_timestamp();
    INSERT INTO minigame_attempts (user_id, game_type, payment_type, status, entry_cost, reward_amount, score, started_at, completed_at)
    SELECT
        u.user_id,
        CASE gs % 2 WHEN 0 THEN 'MEMORY' ELSE 'REACTION' END,
        CASE gs % 2 WHEN 0 THEN 'FREE' ELSE 'TOKEN' END,
        CASE gs % 4 WHEN 0 THEN 'STARTED' ELSE 'COMPLETED' END,
        CASE gs % 2 WHEN 0 THEN 0 ELSE 1 END,
        ROUND((random() * 25)::numeric, 2),
        (random() * 10000)::integer,
        clock_timestamp() - ((u.user_id + gs) % 20000 || ' minutes')::interval,
        CASE WHEN gs % 4 = 0 THEN NULL ELSE clock_timestamp() - ((u.user_id + gs) % 19900 || ' minutes')::interval END
    FROM users u
    CROSS JOIN generate_series(1, v_minigame_attempts_per_user) AS gs;
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'load minigame attempts', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

    FOR v_i IN 1..v_workload_iterations LOOP
        v_start := clock_timestamp();
        UPDATE tokens
        SET current_price = ROUND((current_price * (0.95 + random() * 0.10))::numeric, 2),
            last_update = clock_timestamp();
        GET DIAGNOSTICS v_rows = ROW_COUNT;
        INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'workload update token prices #' || v_i, v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

        v_start := clock_timestamp();
        INSERT INTO token_price_history (token_id, price, recorded_at)
        SELECT token_id, current_price, clock_timestamp()
        FROM tokens;
        GET DIAGNOSTICS v_rows = ROW_COUNT;
        INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'workload append price history #' || v_i, v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

        v_start := clock_timestamp();
        UPDATE user_wallets
        SET quantity = quantity + ROUND((random() * 2 - 1)::numeric, 4)
        WHERE user_id IN (
            SELECT user_id
            FROM users
            WHERE user_id BETWEEN 1 + ((v_i - 1) * 100) AND (v_i * 1000)
        );
        GET DIAGNOSTICS v_rows = ROW_COUNT;
        INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'workload update wallet slice #' || v_i, v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);
    END LOOP;

    v_start := clock_timestamp();
    SELECT COUNT(*) INTO v_rows
    FROM (
        SELECT u.user_id, SUM(w.quantity * t.current_price) AS portfolio_value
        FROM users u
        JOIN user_wallets w ON w.user_id = u.user_id
        JOIN tokens t ON t.token_id = w.token_id
        GROUP BY u.user_id
        ORDER BY portfolio_value DESC
        LIMIT 100
    ) AS leaderboard;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'read leaderboard wallet/token aggregate', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), 'Expected rows: 100');

    v_start := clock_timestamp();
    SELECT COUNT(*) INTO v_rows
    FROM (
        SELECT n.*
        FROM notifications n
        WHERE n.user_id = GREATEST(1, v_user_count / 2)
        ORDER BY n.created_at DESC
        LIMIT 50
    ) AS latest_notifications;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'read latest notifications by user', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), 'Index target: idx_notifications_user_created');

    v_start := clock_timestamp();
    SELECT COUNT(*) INTO v_rows
    FROM (
        SELECT gs.match_id, gs.status, mp.user_id, mp.current_hp, mc.card_type, mc.card_value
        FROM game_sessions gs
        JOIN match_participants mp ON mp.match_id = gs.match_id
        LEFT JOIN match_cards mc ON mc.match_id = gs.match_id AND mc.owner_id = mp.user_id AND mc.is_used = FALSE
        WHERE gs.status = 'BATTLE'
        ORDER BY gs.start_time DESC
        LIMIT 500
    ) AS match_state;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'read active match state join', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

    v_start := clock_timestamp();
    SELECT COUNT(*) INTO v_rows
    FROM (
        SELECT ma.*
        FROM minigame_attempts ma
        WHERE ma.user_id = GREATEST(1, v_user_count / 3)
          AND ma.game_type = 'REACTION'
          AND ma.payment_type = 'TOKEN'
        ORDER BY ma.started_at DESC
        LIMIT 30
    ) AS attempts;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'read minigame access/history query', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), 'Index target: idx_minigame_attempts_user_game_started');

    v_start := clock_timestamp();
    SELECT COUNT(*) INTO v_rows
    FROM (
        SELECT token_id, AVG(price), MIN(price), MAX(price), COUNT(*)
        FROM token_price_history
        WHERE recorded_at > clock_timestamp() - '2 days'::interval
        GROUP BY token_id
    ) AS price_report;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'read token price history aggregate', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), NULL);

    v_start := clock_timestamp();
    DELETE FROM notifications
    WHERE is_read = TRUE
      AND notification_id IN (
          SELECT notification_id
          FROM notifications
          WHERE is_read = TRUE
          ORDER BY notification_id
          LIMIT 1000
      );
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    INSERT INTO stress_results VALUES (DEFAULT, v_run_id, 'delete old/read notification slice', v_rows, v_start, clock_timestamp(), ROUND(EXTRACT(EPOCH FROM (clock_timestamp() - v_start))::numeric * 1000, 3), 'Small delete to test write cleanup path');

    v_line_no := 0;
    FOR v_plan_line IN EXECUTE $q$
        EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT)
        SELECT u.user_id, SUM(w.quantity * t.current_price) AS portfolio_value
        FROM fichestu_stress.users u
        JOIN fichestu_stress.user_wallets w ON w.user_id = u.user_id
        JOIN fichestu_stress.tokens t ON t.token_id = w.token_id
        GROUP BY u.user_id
        ORDER BY portfolio_value DESC
        LIMIT 100
    $q$ LOOP
        v_line_no := v_line_no + 1;
        INSERT INTO stress_explain_lines VALUES (v_run_id, 'leaderboard wallet/token aggregate', v_line_no, v_plan_line);
    END LOOP;

    v_line_no := 0;
    FOR v_plan_line IN EXECUTE $q$
        EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT)
        SELECT n.*
        FROM fichestu_stress.notifications n
        WHERE n.user_id = 5000
        ORDER BY n.created_at DESC
        LIMIT 50
    $q$ LOOP
        v_line_no := v_line_no + 1;
        INSERT INTO stress_explain_lines VALUES (v_run_id, 'latest notifications by user', v_line_no, v_plan_line);
    END LOOP;

    v_line_no := 0;
    FOR v_plan_line IN EXECUTE $q$
        EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT)
        SELECT gs.match_id, gs.status, mp.user_id, mp.current_hp, mc.card_type, mc.card_value
        FROM fichestu_stress.game_sessions gs
        JOIN fichestu_stress.match_participants mp ON mp.match_id = gs.match_id
        LEFT JOIN fichestu_stress.match_cards mc ON mc.match_id = gs.match_id AND mc.owner_id = mp.user_id AND mc.is_used = FALSE
        WHERE gs.status = 'BATTLE'
        ORDER BY gs.start_time DESC
        LIMIT 500
    $q$ LOOP
        v_line_no := v_line_no + 1;
        INSERT INTO stress_explain_lines VALUES (v_run_id, 'active match state join', v_line_no, v_plan_line);
    END LOOP;

    ANALYZE;

    INSERT INTO stress_capacity_report (run_id, relation_name, estimated_rows, table_bytes, index_bytes, total_bytes)
    SELECT
        v_run_id,
        c.relname,
        GREATEST(c.reltuples::bigint, 0),
        pg_table_size(c.oid),
        pg_indexes_size(c.oid),
        pg_total_relation_size(c.oid)
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'fichestu_stress'
      AND c.relkind = 'r'
      AND c.relname NOT LIKE 'stress_%'
    ORDER BY pg_total_relation_size(c.oid) DESC;

    UPDATE stress_runs
    SET finished_at = clock_timestamp()
    WHERE run_id = v_run_id;
END $$;

SELECT
    step_order,
    step_name,
    rows_affected,
    duration_ms,
    notes
FROM stress_results
ORDER BY step_order;

SELECT
    relation_name,
    estimated_rows,
    pg_size_pretty(table_bytes) AS table_size,
    pg_size_pretty(index_bytes) AS index_size,
    pg_size_pretty(total_bytes) AS total_size
FROM stress_capacity_report
ORDER BY total_bytes DESC;

SELECT
    run_id,
    started_at,
    finished_at,
    ROUND(EXTRACT(EPOCH FROM (finished_at - started_at))::numeric, 3) AS total_seconds,
    config
FROM stress_runs
ORDER BY started_at DESC
LIMIT 1;
